name: Feature request - ATIS
title: "[ATIS] "
description: Bugs or issues related to ATIS
labels:
  - ATIS
assignees: marud94, Atriusftw
body:
  - type: markdown
    attributes:
      value: Hello - Thanks for comming with a new possible feature request.
  - type: checkboxes
    id: checkboxes-1
    attributes:
      label: Which part?
      options:
        - label: ATIS generated via EuroScope (vatatis.nz)
        - label: ATIS maker webpage (atis.adbj.no)
        - label: Somewhere else
    validations:
      required: true
  - type: textarea
    id: textarea-2
    attributes:
      label: Suggestion
      description: Provide your suggestion
    validations:
      required: true
