name: Bug report - Euroscope/Sectorfile
title: "[BUG] "
type: bug
description: Bugs related to EuroScope/sectorfile
body:
  - type: markdown
    attributes:
      value: >-
        Hello - Thanks for reporting an issue you have found in the sectorfile
        
        To help us fix your issue it is important that you provide as much information as possible. 
        Screenshots are usually the most contributing factor when trying to debug certain issues.
  - type: textarea
    id: textarea-1
    attributes:
      label: Screenshots
      description: "Important: Provide atleast 1 screenshot of your **whole**
        EuroScope window!"
  - type: textarea
    id: textarea-2
    attributes:
      label: Explaination
      description: Explain the bug
    validations:
      required: true
  - type: textarea
    id: textarea-3
    attributes:
      label: Additional context
      description: Add any other context about the problem here
