name: Feature request - EuroScope/Sectorfile
title: "[Suggestion] "
description: Suggestions for either the sectorfile, ATIS, wiki or other
type: feature
labels:
  - Question / Suggestion
body:
  - type: markdown
    attributes:
      value: Hello - Thanks for comming with a new possible feature request.
  - type: checkboxes
    id: checkboxes-1
    attributes:
      label: Which service?
      options:
        - label: Sectorfile
        - label: ATIS
        - label: Wiki/documentation
        - label: Other
    validations:
      required: true
  - type: textarea
    id: textarea-2
    attributes:
      label: Suggestion
      description: Provide your suggestion
    validations:
      required: true
